# version: '3'
services:
  fastbuka-vendor:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastbuka-vendor:1.0.0
    container_name: fastbuka-vendor
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    command: npm run start
