version: '3'
services:
  web:
    image: fastbuka-app
    build:
      context: .
    ports:
      - "3003:3003"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
    command: npm run start
